version: '3'
services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  web:
     build: docker/nginx
     links:
     - php
     ports:
       - "8081:80"
     volumes:
       - .:/data
  php:
    build: docker/php
    links:
    - db
    tty: true
    restart: always
    volumes:
      - .:/data
